import React from 'react';

function OrganizerDashboardContent() {
    // Your component logic here
    return (
        <div className='text-white'>
            <hr></hr>
            OrganizerDashboardContent
            <hr></hr>
            OrganizerDashboardContent
            <hr></hr>
            OrganizerDashboardContent
            <hr></hr>
            OrganizerDashboardContent
            <hr></hr>
            OrganizerDashboardContent
            <hr></hr>
            vhv
            OrganizerDashboardContent
            <hr></hr>
            vhOrganizerDashboardContent
            <hr></hr>
            OrganizerDashboardContent
            <hr></hr>
            OrganizerDashboardContent
            <hr></hr>
            OrganizerDashboardContent
            <hr></hr>
            OrganizerDashboardContent
            <hr></hr>
            <hr></hr>
            OrganizerDashboardContent
            <hr></hr>
            OrganizerDashboardContent
            <hr></hr>
            OrganizerDashboardContent
            <hr></hr>
            OrganizerDashboardContent
            <hr></hr>
            OrganizerDashboardContent
            <hr></hr>
            vhv
            OrganizerDashboardContent
            <hr></hr>
            vhOrganizerDashboardContent
            <hr></hr>
            OrganizerDashboardContent
            <hr></hr>
            OrganizerDashboardContent
            <hr></hr>
            OrganizerDashboardContent
            <hr></hr>
            OrganizerDashboardContent
            <hr></hr>
            <hr></hr>
            OrganizerDashboardContent
            <hr></hr>
            OrganizerDashboardContent
            <hr></hr>
            OrganizerDashboardContent
            <hr></hr>
            OrganizerDashboardContent
            <hr></hr>
            OrganizerDashboardContent
            <hr></hr>
            vhv
            OrganizerDashboardContent
            <hr></hr>
            vhOrganizerDashboardContent
            <hr></hr>
            OrganizerDashboardContent
            <hr></hr>
            OrganizerDashboardContent
            <hr></hr>
            OrganizerDashboardContent
            <hr></hr>
            OrganizerDashboardContent
            <hr></hr>
            <hr></hr>
            OrganizerDashboardContent
            <hr></hr>
            OrganizerDashboardContent
            <hr></hr>
            OrganizerDashboardContent
            <hr></hr>
            OrganizerDashboardContent
            <hr></hr>
            OrganizerDashboardContent
            <hr></hr>
            vhv
            OrganizerDashboardContent
            <hr></hr>
            vhOrganizerDashboardContent
            <hr></hr>
            OrganizerDashboardContent
            <hr></hr>
            OrganizerDashboardContent
            <hr></hr>
            OrganizerDashboardContent
            <hr></hr>
            OrganizerDashboardContent
            <hr></hr>
        </div>
    );
};

export default OrganizerDashboardContent;

